import Head from "next/head";
import PocoCard from "@/components/PocoCard";
import Carousel from "@/components/Carousel";
import Image from "next/image";
import { getPokemons } from "@/graphQl/queries";
import TextContent from "@/components/TextSection";

export const getStaticProps = async () => {
  const data = await getPokemons();

  return { props: { data } };
};

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>LemonHive - Pokemon Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=" w-full  bg-[url('/Assets/Background.png')] bg-center bg-cover bg-no-repeat">
          <div className="container rounded-md mx-auto text-center py-20  ">
            <Image
              className="mx-auto mb-10"
              src="/Assets/Logo.png"
              alt="pokomon"
              width={200}
              height={200}
            />
            {/* smaller device only */}

            <div className="lg:hidden">
              <Carousel
                data={data?.pokemons?.results}
                types={data?.types?.results}
              />
            </div>

            {/* desktop only */}
            <div className=" hidden lg:grid gap-20 grid-cols-2  md:grid-cols-3 lg:grid-cols-5">
              {data?.pokemons?.results?.slice(0, 10).map((poko, index) => (
                <PocoCard
                  key={index}
                  data={poko}
                  power={data?.types?.results[index]}
                />
              ))}
              {/* cards */}
            </div>
          </div>
        </section>
        {/* textual content */}
        <TextContent />
      </main>
    </>
  );
}
